---
title: "Desempenho dos estudantes no SAEB de 2017"
subtitle: "Mário Fernandes"
author: "PIXRJ - Consultoria"
date: "Dezembro/2021"
output: rmdformats::robobook
code_folding: show

---

```{r setup, include=FALSE}
{library(flexdashboard)
library(readr)
library(stringr)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(scales)
library(treemapify)
library(ggalt)
library(ggrepel)
library(readxl)
}

# base_saeb = read_excel("Base SAEB.xlsx")
# 
# # dependencia administrativa
# base_saeb$depADM5EF <- factor(base_saeb$depADM5EF,levels=c(0,1,2),
#                               labels=c("Municipal","Estadual","Federal"))
# 
# # escolaridade da mãe
# base_saeb$esc_mae5EF <- factor(base_saeb$esc_mae5EF,levels=c(0,1,2,3),
#                               labels=c("Até EF incompleto","EF completo","EM completo",
#                                        "Ensino superior completo ou mais"))
# # escolaridade do pai
# base_saeb$esc_pai5EF <- factor(base_saeb$esc_pai5EF,levels=c(0,1,2,3),
#                               labels=c("Até EF incompleto","EF completo","EM completo",
#                                        "Ensino superior completo ou mais"))
# 
# # raça
# base_saeb$raca5EF <- factor(base_saeb$raca5EF,levels=c(0,1),
#                               labels=c("Branco","Não branco"))
# 
# # turno
# base_saeb$turno5EF <- factor(base_saeb$turno5EF,levels=c(0,1,2),
#                               labels=c("Manhã","Tarde","Noite"))
# 
# # local
# base_saeb$local5EF <- factor(base_saeb$local5EF,levels=c(0,1,2,3),
#                               labels=c("RJ","CE","ES","SP"))
# 
# # sexo
# base_saeb$sexo <- factor(base_saeb$sexo,levels=c(0,1),
#                               labels=c("Feminino","Masculino"))
# 
# # série
# base_saeb$serie <- factor(base_saeb$serie,levels=c(1,2,3),
#                               labels=c("5º ano EF","9º ano EF","3ª série EM"))
# 
# base_saeb = base_saeb |> 
#   filter(serie== "5º ano EF") |> 
#   rename(depADM=depADM5EF, esc_mae= esc_mae5EF, esc_pai= esc_pai5EF, raca=raca5EF, turno=turno5EF, local=local5EF)
# 

base_saeb = read_csv2("base_saeb.csv")
```

### Raça x Proficiência em Português x Escolaridade do pai {.tabset}
```{r fig.align='center', echo=FALSE, message=FALSE, warning=FALSE, fig.width = 14}

# calculando a media e as barras por raca e esc_pai
media_erros <- base_saeb |> 
  group_by(esc_pai,raca) |> 
  summarize(n = n(),
         media = mean(prof_port),
         desvio = sd(prof_port),
         erro.padrao = desvio / sqrt(n))

# gráfico de médias com os erros padrões
media_erros |> 
  ggplot(mapping = aes(x = esc_pai,
                       y = media,
                       group = raca,
                       color = raca)) +
  geom_point(size = 3) +
  geom_errorbar(aes(ymin = media - erro.padrao, 
                    ymax = media + erro.padrao), 
                width = .1) + 
  #ylim(c(3.5,4.5)) +
  labs(x = "Escolaridade do pai",
       y = "Média da proficiência em português",
       color = "Raça",
       title = "Proficiência em Português") + theme_classic() +
  theme(legend.position = "top")  +
  theme(plot.title = element_text(hjust = 0.5, size=14, face="bold"),
        text = element_text(size=15), plot.subtitle = element_text(hjust = 0.5, size=12))
```

### Raça x Proficiência em Matemática x Escolaridade do pai
```{r fig.align='center', echo=FALSE, message=FALSE, warning=FALSE, fig.width = 14}

# calculando a media e as barras por raca e esc_pai
media_erros <- base_saeb |> 
  group_by(esc_pai,raca) |> 
  summarize(n = n(),
         media = mean(prof_mat),
         desvio = sd(prof_mat),
         erro.padrao = desvio / sqrt(n))

# gráfico de médias com os erros padrões
media_erros |> 
  ggplot(mapping = aes(x = esc_pai,
                       y = media,
                       group = raca,
                       color = raca)) +
  geom_point(size = 3) +
  geom_errorbar(aes(ymin = media - erro.padrao, 
                    ymax = media + erro.padrao), 
                width = .1) + 
  #ylim(c(3.5,4.5)) +
  labs(x = "Escolaridade do pai",
       y = "Média da proficiência em matemática",
       color = "Raça",
       title = "Proficiência em Matemática") + theme_classic() +
  theme(legend.position = "top")  +
  theme(plot.title = element_text(hjust = 0.5, size=14, face="bold"),
        text = element_text(size=15), plot.subtitle = element_text(hjust = 0.5, size=12))
```

### depADM x Proficiência em Português x Localização {.tabset}
```{r fig.align='center', echo=FALSE, message=FALSE, warning=FALSE, fig.width = 14}

# calculando a media e as barras por depADM e local
media_erros <- base_saeb |> 
  group_by(local,depADM) |> 
  summarize(n = n(),
         media = mean(prof_port),
         desvio = sd(prof_port),
         erro.padrao = desvio / sqrt(n))

# gráfico de médias com os erros padrões
media_erros |> 
  ggplot(mapping = aes(x = local,
                       y = media,
                       group = depADM,
                       color = depADM)) +
  geom_point(size = 3) +
  labs(x = "Localização",
       y = "Média da proficiência em português",
       color = "Dependência Administrativa",
       title = "Proficiência em Português") + theme_classic() +
  theme(legend.position = "top")  +
  theme(plot.title = element_text(hjust = 0.5, size=14, face="bold"),
        text = element_text(size=15), plot.subtitle = element_text(hjust = 0.5, size=12))
```

### depADM x Proficiência em Matemática x Localização
```{r fig.align='center', echo=FALSE, message=FALSE, warning=FALSE, fig.width = 14}

# calculando a media e as barras por depADM e local
media_erros <- base_saeb |> 
  group_by(local,depADM) |> 
  summarize(n = n(),
         media = mean(prof_mat),
         desvio = sd(prof_mat),
         erro.padrao = desvio / sqrt(n))

# gráfico de médias com os erros padrões
media_erros |> 
  ggplot(mapping = aes(x = local,
                       y = media,
                       group = depADM,
                       color = depADM)) +
  geom_point(size = 3) +
  labs(x = "Localização",
       y = "Média da proficiência em matemática",
       color = "Dependência Administrativa",
       title = "Proficiência em Matemática") + theme_classic() +
  theme(legend.position = "top")  +
  theme(plot.title = element_text(hjust = 0.5, size=14, face="bold"),
        text = element_text(size=15), plot.subtitle = element_text(hjust = 0.5, size=12))
```


### Raça x Proficiência em Português {.tabset}

```{r fig.align='center', echo=FALSE, message=FALSE, warning=FALSE, fig.width = 14}
# Boxplot por turno
# criando um resumo do objeto survey
media_grafico <- base_saeb |> 
  group_by(raca) |> 
  summarize(media = mean(prof_port, na.rm = TRUE))

# criando o gráfico de barras para as médias
media_grafico |>
  ggplot(mapping = aes(x = raca,
                       y = media)) +
  geom_bar(stat = "identity", fill="lightseagreen") +
  labs(x = "Raça",
       y = "Média da Proficiência em Português",
       title = "Proficiência em Português") + theme_classic() +
  theme(legend.position = "top")  +
  theme(plot.title = element_text(hjust = 0.5, size=14, face="bold"),
        text = element_text(size=15), plot.subtitle = element_text(hjust = 0.5, size=12))
```

### Raça x Proficiência em Matemática {.tabset}

```{r fig.align='center', echo=FALSE, message=FALSE, warning=FALSE, fig.width = 14}
# Boxplot por turno
# criando um resumo do objeto survey
media_grafico <- base_saeb |> 
  group_by(raca) |> 
  summarize(media = mean(prof_mat, na.rm = TRUE))

# criando o gráfico de barras para as médias
media_grafico |>
  ggplot(mapping = aes(x = raca,
                       y = media)) +
  geom_bar(stat = "identity", fill="lightseagreen") +
  labs(x = "Raça",
       y = "Média da Proficiência em Matemática",
       title = "Proficiência em Matemática") + theme_classic() +
  theme(legend.position = "top")  +
  theme(plot.title = element_text(hjust = 0.5, size=14, face="bold"),
        text = element_text(size=15), plot.subtitle = element_text(hjust = 0.5, size=12))
```
